config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
    resources :device_brands
    resources :device_models
    resources :service_centers
    resources :device_problems
    resources :activity_statuses
    resources :final_statuses
    resources :parts_inventories
  end

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  resources :profiles, only: [:show, :edit, :update]
  resources :repair_orders, path: 'repair-orders' do
    collection do
      get :device_models
    end
    member do
      post :deliver
    end
  end

  resources :repair_informations, only: [:create, :update, :show]
  root 'home#index'

  resources :home do
    collection do
      post :local_switcher
      get :parts_names
    end
  end

end

app/controllers/admin/activity_statuses_controller.rb
class Admin::ActivityStatusesController < ApplicationController
  before_filter :authenticate_admin_user!, except: [:show, :index]
  before_action :set_admin_activity_status, only: [:show, :edit, :update, :destroy]
  before_action :load_activity_statuses

  layout 'admin'
  # GET /admin/activity_statuses
  # GET /admin/activity_statuses.json
  def index
    @activity_statuses = ActivityStatus.all
  end

  # GET /admin/activity_statuses/1
  # GET /admin/activity_statuses/1.json
  def show
  end

  # GET /admin/activity_statuses/new
  def new
    @activity_status = ActivityStatus.new
  end

  # GET /admin/activity_statuses/1/edit
  def edit
  end

  # POST /admin/activity_statuses
  # POST /admin/activity_statuses.json
  def create
    @activity_status = ActivityStatus.new(admin_activity_status_params)

    respond_to do |format|
      if @activity_status.save
        format.html { redirect_to admin_activity_status_path(@activity_status), notice: 'Activity status was successfully created.' }
        format.json { render :show, status: :created, location: @activity_status }
      else
        format.html { render :new }
        format.json { render json: @activity_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/activity_statuses/1
  # PATCH/PUT /admin/activity_statuses/1.json
  def update
    respond_to do |format|
      if @activity_status.update(admin_activity_status_params)
        format.html { redirect_to admin_activity_status_path(@activity_status), notice: 'Activity Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_status }
      else
        format.html { render :edit }
        format.json { render json: @activity_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/activity_statuses/1
  # DELETE /admin/activity_statuses/1.json
  def destroy
    @activity_status.destroy
    respond_to do |format|
      format.html { redirect_to admin_activity_statuses_url, notice: 'Activity Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_activity_status
    @activity_status = ActivityStatus.find(params[:id])
  end

  def load_activity_statuses
    @activity_statuses = ActivityStatus.order('updated_at DESC')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_activity_status_params
    params.require(:activity_status).permit(:name, :status)
  end
end

app/views/admin/activity_statuses/_form.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <h1><%= @activity_status.new_record? ? 'New Activity Status' : 'Edit Activity Status' %></h1>

  <div class="row">
    <div class="col-md-8">
      <%= form_for([:admin, @activity_status], :html => {role: 'form'}) do |f| %>

          <%= render partial: 'shared/errors', :locals => {object: @activity_status} %>

          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <h5>Activity Status</h5>
            </div>

            <div class="ibox-content">

              <div class="form-group">
                <%= f.label 'Name' %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Name', required: true %>
              </div>

              <div class="form-group">
                <div class="switch">
                  <div class="onoffswitch">
                    <%= f.check_box :status, id: 'example1', class: 'onoffswitch-checkbox'  %>
                    <!--<input type="checkbox" id="example1" class="onoffswitch-checkbox" name="service_center[is_active]" checked="" value="true">-->
                    <label for="example1" class="onoffswitch-label">
                      <span class="onoffswitch-inner"></span>
                      <span class="onoffswitch-switch"></span>
                    </label>
                  </div>
                </div>
              </div>

            </div>
          </div>

          <div class="actions form-group">
            <%= f.submit class: 'btn btn-sm btn-primary pull-left m-t-n-xs' %>
            <%= link_to 'Back', admin_activity_statuses_path, class: 'btn btn-sm btn-white m-t-n-xs margin-left' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/activity_statuses/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Activity Status</h5>
        </div>
        <div class="ibox-content">

          <div class="table-responsive">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
              <!--<div class="html5buttons">-->
                <!--<div class="dt-buttons btn-group">-->
                  <!--<a class="btn btn-default buttons-copy buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>Copy</span></a><a class="btn btn-default buttons-csv buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>CSV</span></a><a class="btn btn-default buttons-excel buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>Excel</span></a><a class="btn btn-default buttons-pdf buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>PDF</span></a><a class="btn btn-default buttons-print" tabindex="0" aria-controls="DataTables_Table_0"><span>Print</span></a>-->
                <!--</div>-->
              <!--</div>-->

              <!--<div id="DataTables_Table_0_filter" class="dataTables_filter">-->
                <!--<label>Search:<input type="search" class="form-control input-sm" placeholder="" aria-controls="DataTables_Table_0"></label>-->
              <!--</div>-->

              <!--<div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 1 to 10-->
                <!--of 57 entries-->
              <!--</div>-->

              <table class="table table-striped table-bordered table-hover dataTables-example dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info" role="grid">
                <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 168px;" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">
                    Name
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 204px;" aria-label="Browser: activate to sort column ascending">
                    Status
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 95px;" aria-label="CSS grade: activate to sort column ascending">
                    Action
                  </th>
                </tr>
                </thead>
                <tbody>
                <% @activity_statuses.each_with_index do |activity, i| %>
                    <tr class="gradeA <%= i%2 == 0 ? 'odd' : 'even' %>" role="row">
                      <td class="sorting_1"><%= activity.name %></td>
                      <td><%= activity.status %></td>
                      <td>
                        <%= link_to 'Show', admin_activity_status_path(activity), :class => 'btn btn-white btn-xs', 'data-no-turbolink' => true %>
                        <%= link_to 'Edit', edit_admin_activity_status_path(activity), :class => 'btn btn-primary btn-xs' if admins? %>
                        <%= link_to 'Delete', admin_activity_status_path(activity), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-xs btn-danger' if admins? %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/activity_statuses/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row m-b-lg m-t-lg">
    <div class="col-md-8">
      <table class="table small m-b-xs">
        <tbody>
        <tr>
          <td>
            Name <strong><%= @activity_status.name %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Status <strong><%= @activity_status.status %></strong>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to 'Edit', edit_admin_activity_status_path(@activity_status), class: 'btn btn-sm btn-white m-t-n-xs' if admins? %>
  <%= link_to 'back', admin_activity_statuses_path, class: 'mergin-left btn btn-sm btn-white m-t-n-xs' %>
</div>