config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
    resources :device_brands
    resources :device_models
    resources :service_centers
    resources :device_problems
    resources :activity_statuses
    resources :final_statuses
    resources :parts_inventories
  end

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  resources :profiles, only: [:show, :edit, :update]
  resources :repair_orders, path: 'repair-orders' do
    collection do
      get :device_models
    end
    member do
      post :deliver
    end
  end

  resources :repair_informations, only: [:create, :update, :show]
  root 'home#index'

  resources :home do
    collection do
      post :local_switcher
      get :parts_names
    end
  end

end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(object.errors.count, "error") %> prohibited this model from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="pull-right">
    Property of <strong>Electra</strong> Mobile.
  </div>
  <div>
    <strong>Copyright</strong> CodeKnob &copy; 2016
  </div>
</div>

app/views/shared/_nav_sidebar.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">

      <li class="nav-header">
        <div class="dropdown profile-element"> <span>
            <%= image_tag profile_photo, :class => 'img-circle'%>
                             </span>
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs">
                              <strong class="font-bold"><%= current_user ? current_user.profile.first_name : "Guest" %>&nbsp;<%= current_user ? current_user.profile.last_name : "User" %></strong>
                            </span>
                            <span class="text-muted text-xs block"><%= current_user.roles.first.name if current_user %> <b class="caret"></b></span>
                            </span> </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a href="<%= current_user ? profile_path(current_user.profile) : 'javascript:void(0)' %>"><%= t('sidebar.profile') %></a></li>
            <li class="divider"></li>
            <li><%= link_to t('header.logout'), destroy_user_session_path, :method => 'delete' %></li>
          </ul>
        </div>

        <div class="logo-element">
          Admin
        </div>
      </li>
      <% if admins? %>
          <li>
            <a href="javascript:;"><i class="fa fa-users"></i> <span class="nav-label"><%= t('sidebar.users.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_user_path %>"><%= t('sidebar.users.new') %></a></li>
              <li><a href="<%= admin_users_path %>"><%= t('sidebar.users.all') %></a></li>
            </ul>
          </li>

          <li>
            <a href="javascript:;"><i class="fa fa-plug"></i> <span class="nav-label"><%= t('sidebar.service_centers.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_service_center_path %>"><%= t('sidebar.service_centers.new') %></a></li>
              <li><a href="<%= admin_service_centers_path %>"><%= t('sidebar.service_centers.all') %></a></li>
            </ul>
          </li>
          <li>
            <a href="javascript:;"><i class="fa fa-globe"></i> <span class="nav-label"><%= t('sidebar.device_brands.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_device_brand_path %>"><%= t('sidebar.device_brands.new') %></a></li>
              <li><a href="<%= admin_device_brands_path %>"><%= t('sidebar.device_brands.all') %></a></li>
            </ul>
          </li>
          <li>
            <a href="javascript:;"><i class="fa fa-tablet"></i> <span class="nav-label"><%= t('sidebar.device_models.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_device_model_path %>"><%= t('sidebar.device_models.new') %></a></li>
              <li><a href="<%= admin_device_models_path %>"><%= t('sidebar.device_models.all') %></a></li>
            </ul>
          </li>
          <li>
            <a href="javascript:;"><i class="fa fa-bug"></i> <span class="nav-label"><%= t('sidebar.device_problems.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_device_problem_path %>"><%= t('sidebar.device_problems.new') %></a></li>
              <li><a href="<%= admin_device_problems_path %>"><%= t('sidebar.device_problems.all') %></a></li>
            </ul>
          </li>

          <li>
            <a href="javascript:;"><i class="fa fa-check"></i> <span class="nav-label"><%= t('sidebar.activity_status.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_activity_status_path %>"><%= t('sidebar.activity_status.new') %></a></li>
              <li><a href="<%= admin_activity_statuses_path %>"><%= t('sidebar.activity_status.all') %></a></li>
            </ul>
          </li>

          <!--<li>-->
            <!--<a href="javascript:;"><i class="fa fa-signal"></i> <span class="nav-label"><%#= t('sidebar.device_status.title') %></span><span class="fa arrow"></span></a>-->
            <!--<ul class="nav nav-second-level collapse in">-->
              <!--<li><a href="<%#= new_admin_device_status_path %>"><%#= t('sidebar.device_status.new') %></a></li>-->
              <!--<li><a href="<%#= admin_device_statuses_path %>"><%#= t('sidebar.device_status.all') %></a></li>-->
            <!--</ul>-->
          <!--</li>-->

          <li>
            <a href="javascript:;"><i class="fa fa-tag"></i> <span class="nav-label"><%= t('sidebar.final_status.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_admin_final_status_path %>"><%= t('sidebar.final_status.new') %></a></li>
              <li><a href="<%= admin_final_statuses_path %>"><%= t('sidebar.final_status.all') %></a></li>
            </ul>
          </li>

      <% elsif current_user && current_user.is_receptionist? %>
          <li>
            <a href="javascript:;"><i class="fa fa-tag"></i> <span class="nav-label"><%= t('repair_order.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= new_repair_order_path %>"><%= t('repair_order.new') %></a></li>
              <li><a href="<%= repair_orders_path %>"><%= t('repair_order.all') %></a></li>
            </ul>
          </li>
      <% else %>
          <li>
            <a href="javascript:;"><i class="fa fa-tag"></i> <span class="nav-label"><%= t('repair_order.title') %></span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in">
              <li><a href="<%= repair_orders_path %>"><%= t('repair_order.all') %></a></li>
              <li><a href="<%= repair_orders_path %>"><%= t('repair_order.my_jobs') %></a></li>
            </ul>
          </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/shared/_nav_topbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <!--<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>-->
      <!--<form role="search" class="navbar-form-custom" action="#">-->
      <!--<div class="form-group">-->
      <!--<input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">-->
      <!--</div>-->
      <!--</form>-->
    </div>


    <ul class="nav navbar-top-links navbar-right">
      <li>
        <%= form_tag local_switcher_home_index_path, :class => 'locale' do %>
            <%= select_tag 'locale_set', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()' %>
        <% end %>
      </li>
      <% if admins? %>
          <li>
            <span class="m-r-sm text-muted welcome-message">
              <%= link_to t('header.dashboard'), admin_dashboard_path %>
            </span>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="javascript:void(0)">
              <%= t('header.inventory.title') %> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
              <li>
                <a href="<%= new_admin_parts_inventory_path %>">
                  <div>
                    <%= t('header.inventory.new') %>
                  </div>
                </a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="<%= admin_parts_inventories_path %>">
                  <div>
                    <%= t('header.inventory.all') %>
                  </div>
                </a>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="javascript:void(0)">
              <%= t('repair_order.title') %> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
              <li>
                <a href="<%= new_repair_order_path %>">
                  <div>
                    <%= t('repair_order.new') %>
                  </div>
                </a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="<%= repair_orders_path %>">
                  <div>
                    <%= t('repair_order.all') %>
                  </div>
                </a>
              </li>
            </ul>
          </li>

      <% end %>

      <li>
        <%= link_to destroy_user_session_path, :method => 'delete' do %>
            <i class="fa fa-sign-out"></i> <%= t('header.logout') %>
        <% end %>
      </li>
    </ul>

  </nav>
</div>