config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
    resources :device_brands
    resources :device_models
    resources :service_centers
    resources :device_problems
    resources :activity_statuses
    resources :final_statuses
    resources :parts_inventories
  end

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  resources :profiles, only: [:show, :edit, :update]
  resources :repair_orders, path: 'repair-orders' do
    collection do
      get :device_models
    end
    member do
      post :deliver
    end
  end

  resources :repair_informations, only: [:create, :update, :show]
  root 'home#index'

  resources :home do
    collection do
      post :local_switcher
      get :parts_names
    end
  end

end

app/models/repair_order.rb
class RepairOrder < ActiveRecord::Base

  # class methods
  serialize :device_condition
  serialize :accessories_present

  # associations
  belongs_to :device_brand
  belongs_to :device_model
  belongs_to :service_center
  belongs_to :creator, :class_name => 'User'
  has_many :repair_assignments, :dependent => :destroy
  has_one :repair_information, :dependent => :destroy
  accepts_nested_attributes_for :repair_assignments

  # uploads
  mount_uploader :invoice, OrderInvoiceUploader

  # validations
  validates_presence_of :device_brand_id, :device_model_id, :service_center_id,
                        :customer_name, :customer_email, :customer_contact_no,
                        :imei1
  validates :imei2, length: {is: 15}, allow_blank: true
  validates :imei1, length: {is: 15}, allow_blank: false

  # class variables
  ACCESORIES = {
    1 => 'Battery',
    2 => 'Back Cover',
    3 => 'Adaptor',
    4 => 'USB Cable',
    5 => 'Full Charger',
    6 => 'Handsfree',
    7 => 'Stylus / Stick',
    8 => 'MMC Card',
    9 => 'SIM Card'
  }
  DEVICE_CONDITIONS = {
    1 => 'Physical Damaged',
    2 => 'Liquid Damaged',
    3 => 'Battery Bulged',
    4 => 'Accessories Damaged',
    5 => 'Third Party Handled',
    6 => 'Unit OUT Warranty'
  }

  # callbacks
  after_create :construct_repair_information

  # scopes

  # instance methods

  def construct_repair_information
    if self.repair_assignments.present?
      self.create_repair_information(:repair_assignment_id => self.repair_assignments.last.id)
    end
  end

end

app/controllers/repair_orders_controller.rb
class RepairOrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_repair_order, only: [:show, :edit, :update, :destroy, :deliver]
  before_filter :can_crud?, only: [:create, :edit, :new, :update]

  layout 'admin'
  # GET /repair_orders
  # GET /repair_orders.json
  def index
    if current_user.is_super_admin?
      @repair_orders = RepairOrder.includes(:repair_information, :repair_assignments).all
    else
      @repair_orders = current_user.profile.service_center.repair_orders.includes(:repair_information, :repair_assignments)
    end
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'repair_orders',
               template: 'repair_orders/index.pdf.erb',
               encoding: 'utf8',
               layout: 'layouts/pdf.html.erb',
               show_as_html: params[:debug].present?
      end
    end
  end

  # GET /repair_orders/1
  # GET /repair_orders/1.json
  def show
    @repair_order = RepairOrder.includes(:device_model, :device_brand, :service_center).find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice",
               template: 'repair_orders/show.pdf.erb',
               encoding: 'utf8',
               layout: 'layouts/pdf.html.erb',
               show_as_html: params[:debug].present?
      end
    end
  end

  # GET /repair_orders/new
  def new
    redirect_to :back, notice: 'You cannot create Repair Order.' if current_user.role?(:super_admin)
    @repair_order = RepairOrder.new
    @repair_assignment = @repair_order.repair_assignments.build
  end

  # GET /repair_orders/1/edit
  def edit
    redirect_to repair_orders_path if current_user != @repair_order.creator
  end

  # POST /repair_orders
  # POST /repair_orders.json
  def create
    @repair_order = current_user.repair_orders.new(repair_order_params)

    respond_to do |format|
      if @repair_order.save
        format.html { redirect_to @repair_order, notice: 'Repair order was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order }
      else
        format.html { render :new }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_orders/1
  # PATCH/PUT /repair_orders/1.json
  def update
    respond_to do |format|
      if @repair_order.update(repair_order_params)
        format.html { redirect_to @repair_order, notice: 'Repair order was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order }
      else
        format.html { render :edit }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_orders/1
  # DELETE /repair_orders/1.json
  def destroy
    @repair_order.destroy
    respond_to do |format|
      format.html { redirect_to repair_orders_url, notice: 'Repair order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def device_models
    @device_brand = DeviceBrand.find(params[:brand_id])
    @device_models = @device_brand.device_models
    @repair_order = params[:order_id].present? ? RepairOrder.find(params[:order_id]) :nil
  end

  def deliver
    @repair_order.update_column(:delivered, true)
    redirect_to repair_orders_path, notice: 'Repair order was successfully delivered.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_repair_order
    @repair_order = RepairOrder.find(params[:id])
    @repair_assignment = @repair_order.repair_assignments.where(:transferred_job => false).last
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repair_order_params
    params.require(:repair_order).permit(:device_brand_id, :device_model_id, :service_center_id, :imei1, :imei2,
                                         :purchase_date, :warranty, :customer_name, :customer_contact_no,
                                         :customer_email, :customer_address, :dealer, :full_boxed, :remarks,
                                         :invoice, :delivery_date, :device_condition => [], :accessories_present => [],
                                         :repair_assignments_attributes => [:assigner_id, :assigned_id, :transferred_job, :id]
    )
  end

  def can_crud?
    if current_user.is_admin? || current_user.is_receptionist?
      return true
    else
      return false
    end
  end
end

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper

  def all_service_centers
    ServiceCenter.order('created_at DESC')
  end

  def all_device_brands
    DeviceBrand.order('created_at DESC')
  end

  def select_device_model(brand)
    DeviceBrand.find(brand).device_models.order('created_at DESC')
  end

  def service_center_employees
    current_profile = current_user.profile
    all_employees = current_profile.service_center.profiles.where.not(id: current_profile.id)
    return all_employees
  end
end

app/views/repair_orders/_device_models.html.erb
<div class="form-group">
  <%= label_tag t('repair_order.device_model'), {}, class: 'sr-only' %>
  <%= select_tag "repair_order[device_model_id]",
                 options_for_select(brand.device_models.collect { |dm| [dm.name,  dm.id] },
                                    :selected => order.nil? ? '' : order.device_model_id),
                                    :prompt => "#{t('repair_order.device_model_prompt')}",
                                    :class => "form-control m-b"
  %>
</div>

<div class="form-group">
  <%= label_tag t('repair_order.device_brand'), {}, class: 'sr-only' %>
  <%= text_field_tag "repair_order[imei1]", order.nil? ? '' : order.imei1 ,
                     class: 'form-control', placeholder: t('repair_order.imei1') %>
</div>

<div class="form-group">
  <%= label_tag t('repair_order.device_brand'), {}, class: 'sr-only' %>
  <%= text_field_tag "repair_order[imei2]", order.nil? ? '' : order.imei2 ,
                     class: 'form-control', placeholder: t('repair_order.imei2') %>
</div>

app/views/repair_orders/_form.html.erb
<div class="wrapper wrapper-content animated fadeInRight repair-order-form">
  <h1><%= @repair_order.new_record? ? t('repair_order.new') : t('repair_order.edit') %></h1>

  <div class="row">
    <%= form_for(@repair_order, :html => {class: '', role: 'form', multipart: true}) do |f| %>
        <div class="col-md-7">

          <%= render partial: 'shared/errors', :locals => {object: @repair_order} %>

          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <h5><%= t('repair_order.header') %></h5>
            </div>

            <div class="ibox-content">

              <div class="form-group">
                <%= f.label t('repair_order.service_center'), class: 'sr-only' %>
                <%= f.select :service_center_id,
                             options_for_select(all_service_centers.collect { |sc| [sc.name, sc.id] },
                                                @repair_order.service_center_id),
                             {prompt: t('repair_order.service_center_prompt')},
                             {required: 'true', class: 'form-control m-b'}
                %>
              </div>

              <div class="form-group">
                <%= f.label t('repair_order.device_brand'), class: 'sr-only' %>
                <%= f.select :device_brand_id,
                             options_for_select(all_device_brands.collect { |brand| [brand.name, brand.id] },
                                                @repair_order.device_brand_id),
                             {prompt: t('repair_order.device_brand_prompt')},
                             {required: 'true', class: 'form-control m-b'}
                %>
              </div>

              <div id="job-model-selection">
                <div class="device-brand-models-dd">
                    <% unless @repair_order.new_record? %>
                        <%= render :partial => 'repair_orders/device_models', :locals => {:order => @repair_order, :brand => @repair_order.device_brand} %>
                    <% end %>
                </div>
              </div>

              <div class="form-group" id="device-purchase-datepicker">
                <div class="row">
                  <div class="col-md-3">
                    <%= label_tag t('repair_order.purchase_date'), t('repair_order.purchase_date'), class: 'labl-wrap' %>
                  </div>
                  <div class="col-md-9">
                    <%= f.text_field :purchase_date, class: 'form-control', id: 'dateP', placeholder: t('repair_order.purchase_date') %>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <%= label_tag t('repair_order.warranty') %>
                    <div class="switch">
                      <div class="onoffswitch">
                        <%= f.check_box :warranty, id: 'example11', class: 'onoffswitch-checkbox'  %>
                        <label for="example11" class="onoffswitch-label of-lab-11">
                          <span class="onoffswitch-inner"></span>
                          <span class="onoffswitch-switch"></span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <%= label_tag t('repair_order.full_boxed') %>
                    <div class="switch">
                      <div class="onoffswitch">
                        <%= f.check_box :full_boxed, id: 'example12', class: 'onoffswitch-checkbox'  %>
                        <label for="example12" class="onoffswitch-label of-lab-12">
                          <span class="onoffswitch-inner"></span>
                          <span class="onoffswitch-switch"></span>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-3">
                    <%= label_tag t('repair_order.dealer'), t('repair_order.dealer'), class: 'labl-wrap' %>
                  </div>
                  <div class="col-md-9">
                    <%= f.text_field :dealer, class: 'form-control', placeholder: t('repair_order.dealer'), required: true %>
                  </div>
                </div>
              </div>

              <div class="form-group hashable-attributes">
                <div class="row">
                  <div class="col-md-6">
                    <%= label_tag t('repair_order.accessory') %><br>
                    <% RepairOrder::ACCESORIES.each_pair do |accessory_k, accessory_v| %>
                        <%= check_box_tag "repair_order[accessories_present][]", accessory_k,
                                           @repair_order.accessories_present.present? ? @repair_order.accessories_present.include?(accessory_k.to_s) : false %>
                        <label class="loop-chk-b"><%= accessory_v %></label><br>
                    <% end %>
                  </div>
                  <div class="col-md-6">
                    <%= label_tag t('repair_order.condition') %><br>
                    <% RepairOrder::DEVICE_CONDITIONS.each_pair do |condition_k, condition_v| %>
                        <%= check_box_tag "repair_order[device_condition][]", condition_k,
                                          @repair_order.accessories_present.present? ? @repair_order.device_condition.include?(condition_k.to_s) : false %>
                        <label class="loop-chk-b"><%= condition_v %></label><br>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <%= f.label t('repair_order.remarks'), class: 'sr-only' %>
                <%= f.text_area :remarks, class: 'form-control', placeholder: t('repair_order.remarks'), rows: '3' %>
              </div>

              <div class="form-group" id="device-delivery-datepicker">
                <div class="row">
                  <div class="col-md-3">
                    <%= label_tag t('repair_order.delivery_date'), t('repair_order.delivery_date'), class: 'labl-wrap' %>
                  </div>
                  <div class="col-md-9">
                    <%= f.text_field :delivery_date, class: 'form-control', id: 'dateD', placeholder: t('repair_order.delivery_date') %>
                  </div>
                </div>
                <%= label_tag t('repair_order.delivery_text'), t('repair_order.delivery_text'), class: 'alert alert-info' %>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-2">
                    <%= label_tag t('repair_order.invoice') %>
                  </div>
                  <div class="col-md-10">
                    <%= f.file_field :invoice, class: '', placeholder: t('repair_order.invoice') %>
                  </div>
                </div>
              </div>

            </div>
          </div>

          <div class="actions form-group">
            <%= f.submit @repair_order.new_record? ? t('repair_order.create') : t('repair_order.update'), class: 'btn btn-sm btn-primary pull-left m-t-n-xs' %>
            <%= link_to t('repair_order.back'), repair_orders_path, class: 'btn btn-sm btn-white m-t-n-xs margin-left' %>
          </div>
        </div>

        <div class="col-md-5">
          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <h5><%= t('repair_order.customer.header') %></h5>
            </div>

            <div class="ibox-content">

              <div class="form-group">
                <%= f.label t('repair_order.customer.name'), class: 'sr-only' %>
                <%= f.text_field :customer_name, class: 'form-control', placeholder: t('repair_order.customer.name'), required: true %>
              </div>
              <div class="form-group">
                <%= f.label t('repair_order.customer.email'), class: 'sr-only' %>
                <%= f.email_field :customer_email, class: 'form-control', placeholder: t('repair_order.customer.email'), required: true %>
              </div>
              <div class="form-group">
                <%= f.label t('repair_order.customer.phone'), class: 'sr-only' %>
                <%= f.text_field :customer_contact_no, class: 'form-control', placeholder: t('repair_order.customer.phone'), required: true %>
              </div>
              <div class="form-group">
                <%= f.label t('repair_order.customer.address'), class: 'sr-only' %>
                <%= f.text_area :customer_address, class: 'form-control', placeholder: t('repair_order.customer.address'), rows: '2' %>
              </div>

            </div>
          </div>
          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <h5><%= t('repair_order.assignment.title') %></h5>
            </div>

            <div class="ibox-content">
              <%= f.fields_for :repair_assignments do |ff| %>
                  <div class="form-group">
                    <%= ff.select :assigned_id,
                                 options_for_select(service_center_employees.collect { |sc| [sc.full_name, sc.user.id] },
                                                    @repair_assignment.present? ? @repair_assignment.assigned_id : nil),
                                 {prompt: t('repair_order.assignment.select_text')},
                                 {required: 'true', class: 'form-control m-b'}
                    %>
                    <%= ff.hidden_field :assigner_id, value: current_user.id  %>
                    <%= ff.hidden_field :transferred_job, value: false  %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script>
    $("#repair_order_device_brand_id").change(function () {
        var category_name = $("#repair_order_device_brand_id").find("option:selected").text(),
                select_label = "<%= t("repair_order.device_brand_prompt")%>",
                order_id = '<%= @repair_order.new_record? ? '' : @repair_order.id %>';
        if (category_name != select_label) {
            $(".device-brand-models-dd").show();
            $.ajax({
                url: "<%= device_models_repair_orders_path %>",
                data: {brand_id: this.value, order_id: order_id},
                method: "get"
            })
        } else {
            $(".device-brand-models-dd").hide();
        }

    });
    $(function() {
        $('#device-purchase-datepicker #dateP').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy"
        });
        $('#device-delivery-datepicker #dateD').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy"
        });
    });
</script>

app/views/repair_orders/device_models.js.erb
$(".device-brand-models-dd").html('<%= escape_javascript(render(:partial => 'repair_orders/device_models', :locals => {:brand => @device_brand, :order => @repair_order}))%>')

app/views/repair_orders/edit.html.erb
<%= render 'form' %>

app/views/repair_orders/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Repair Orders tabular view</h5>
        </div>
        <div class="ibox-content">

          <div class="table-responsive">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
              <div class="html5buttons">
                <div class="dt-buttons btn-group">
                  <a href="<%= repair_orders_path(format: :pdf) %>" target="_blank" class="btn btn-default buttons-pdf buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>PDF</span></a>
                  <!--<a class="btn btn-default buttons-copy buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>Copy</span></a>-->
                  <!--<a class="btn btn-default buttons-csv buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>CSV</span></a>-->
                  <!--<a class="btn btn-default buttons-excel buttons-html5" tabindex="0" aria-controls="DataTables_Table_0"><span>Excel</span></a>-->
                  <!--<a class="btn btn-default buttons-print" tabindex="0" aria-controls="DataTables_Table_0"><span>Print</span></a>-->
                </div>
              </div>



              <table class="table table-striped table-bordered table-hover dataTables-example dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info" role="grid">
                <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 168px;" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">
                    Device Name
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 204px;" aria-label="Browser: activate to sort column ascending">
                    Assigned (To/By)
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 204px;" aria-label="Browser: activate to sort column ascending">
                    Customer Info.
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 176px;" aria-label="Platform(s): activate to sort column ascending">
                    Device Condition
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 140px;" aria-label="Engine version: activate to sort column ascending">
                    Service Center
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 95px;" aria-label="CSS grade: activate to sort column ascending">Action</th>
                </tr>
                </thead>
                <tbody>
                <% @repair_orders.each_with_index do |order, i| %>
                    <tr class="gradeA <%= i%2 == 0 ? 'odd' : 'even' %>" role="row">
                      <td class="sorting_1">
                        <%= order.device_model.name %> | <%= order.device_brand.name %>
                        <% if order.repair_information.deliverable %>
                            <span class="badge badge-success"><%= order.delivered ? t('repair_order.deliver') : t('repair_order.deliverd') %></span><br/><br/>
                            <% if current_user.role?(:receptionist) %><%= link_to t('repair_order.delivery'), deliver_repair_order_path(order), method: 'post', data: { confirm: t('repair_order.confirm_deliver') }  %><% end %>
                        <% end %>
                      </td>
                      <td>
                        <p>To: <%= order.repair_assignments.last.assigned.profile.full_name %> </p>
                        <p>By: <%= order.repair_assignments.last.assigner.profile.full_name %> </p>
                      </td>
                      <td class="center">
                        <p><%= order.customer_name %></p>
                        <p><%= order.customer_contact_no %></p>
                        <p><%= order.customer_email %></p>
                      </td>
                      <td class="center">
                        <% order.device_condition.each do |con| %>
                            <p><%= RepairOrder::DEVICE_CONDITIONS[con.to_i] %></p>
                        <% end %>
                      </td>
                      <td><%= order.service_center.name %></td>
                      <td>
                        <%= link_to 'Show', repair_order_path(order), :class => 'btn btn-white btn-xs' %>
                        <%= link_to 'Edit', edit_repair_order_path(order), :class => 'btn btn-primary btn-xs' %>
                        <%= link_to 'Delete', repair_order_path(order), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-xs btn-danger' %>
                        <% if is_assigned_technician(order) && !order_delivered(order) %>
                            <%= link_to 'Repair', repair_information_path(order.repair_information), :class => 'btn btn-xs btn-info' %>
                        <% end %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/repair_orders/new.html.erb
<%= render 'form' %>

app/views/repair_orders/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>Invoice</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= admin_dashboard_path %>">Home</a>
      </li>
      <li>
        <a href="<%= repair_orders_path %>">Repair Orders</a>
      </li>
      <li class="active">
        <strong>Invoice</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-4">
    <div class="title-action">
      <a href="<%= edit_repair_order_path(@repair_order) %>" class="btn btn-white"><i class="fa fa-pencil"></i> Edit </a>
      <%= link_to repair_order_path(@repair_order, format: :pdf), class: "btn btn-primary", target: '_blank' do %>
          <i class="fa fa-file-pdf-o"></i> PDF Invoice <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">
      <div class="ibox-content p-xl">
        <div class="row">
          <div class="col-sm-6">
            <h5>From:</h5>
            <address>
              <strong>Electra Servicing Center</strong><br>
              <%= @repair_order.service_center.name %><br>
              <%= @repair_order.service_center.address %><br>
              <abbr title="Phone">P:</abbr> <%= @repair_order.service_center.phone %>
            </address>
          </div>

          <div class="col-sm-6 text-right">
            <h4>Invoice No.</h4>
            <h4 class="text-navy">INV-000567F7-00</h4>
            <span>To:</span>
            <address>
              <strong><%= @repair_order.customer_name %></strong><br>
              <%= @repair_order.customer_address %><br>
              <%= @repair_order.customer_email %><br>
              <abbr title="Phone">P:</abbr> <%= @repair_order.customer_contact_no %>
            </address>
            <p>
              <span><strong>Invoice Date:</strong> <%= @repair_order.created_at.strftime('%v') %></span><br>
              <span><strong>Due Date:</strong> <%= @repair_order.delivery_date.strftime('%v') %></span>
            </p>
          </div>
        </div>

        <div class="table-responsive m-t">
          <table class="table invoice-table">
            <thead>
            <tr>
              <th>Device</th>
              <th>IMEI-1</th>
              <th>Device Condition</th>
              <th>Accessories</th>
              <th>Dealer</th>
              <th>Warranty</th>
              <!--<th>Total Price</th>-->
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><div><strong><%= @repair_order.device_model.name %></strong></div>
                <small>Product of: <%= @repair_order.device_brand.name %></small></td>
              <td><%= @repair_order.imei1 %></td>
              <td>
                <% @repair_order.device_condition.each do |con| %>
                    <%= RepairOrder::DEVICE_CONDITIONS[con.to_i] %><br>
                <% end %>
              </td>
              <td>
                <% @repair_order.accessories_present.each do |acc| %>
                    <%= RepairOrder::ACCESORIES[acc.to_i] %><br>
                <% end %>
              </td>
              <td><%= @repair_order.dealer %></td>
              <td><%= @repair_order.warranty ? 'Warranty present' : 'Warranty NOT present' %></td>
            </tr>

            </tbody>
          </table>
        </div><!-- /table-responsive -->

        <!--<table class="table invoice-total">-->
          <!--<tbody>-->
          <!--<tr>-->
            <!--<td><strong>Sub Total :</strong></td>-->
            <!--<td>$1026.00</td>-->
          <!--</tr>-->
          <!--<tr>-->
            <!--<td><strong>TAX :</strong></td>-->
            <!--<td>$235.98</td>-->
          <!--</tr>-->
          <!--<tr>-->
            <!--<td><strong>TOTAL :</strong></td>-->
            <!--<td>$1261.98</td>-->
          <!--</tr>-->
          <!--</tbody>-->
        <!--</table>-->
        <!--<div class="text-right">-->
          <!--<button class="btn btn-primary"><i class="fa fa-dollar"></i> Make A Payment</button>-->
        <!--</div>-->
        <% if @repair_order.remarks.present? %>
            <div class="well m-t"><strong>Comments</strong>
              <%= @repair_order.remarks %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>